// @ts-nocheck: Script used only for building ruby code
//
// Run this script to compile all *.rb files to *.ts files in a directory:
//   node ./scripts/compile-rb.js ./src/patches/

// reference: https://docs.asciidoctor.org/asciidoctor.js/latest/extend/extensions/compile-ruby-extension/

import fs from 'node:fs';
import path from 'node:path';
import { Builder } from 'opal-compiler';

function template(sourceFileName, opalCode) {
  return `
/* eslint-disable */
// @ts-nocheck

// Generated by compiling ./src/patches/${sourceFileName}
// reference: https://docs.asciidoctor.org/asciidoctor.js/latest/extend/extensions/compile-ruby-extension/

function patch() {

${opalCode}

}
export default { patch };
`.trimStart();
}

function main(dirpath) {
  const builder = Builder.create();
  // for all *.rb files in this directory
  for (const fileName of fs.readdirSync(dirpath)) {
    if (fileName.endsWith('.rb')) {
      const filePath = path.join(dirpath, fileName);
      const opalCode = builder.build(filePath).toString();
      const jsCode = template(fileName, opalCode);
      fs.writeFileSync(filePath.replace(/.rb$/, '.ts'), jsCode);
    }
  }
}

const args = process.argv;
if (args.length < 3) {
  console.error('Usage: node compile-rb.js');
  process.exit(1);
}
main(args[2]);
